/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_FFmpeg */

#ifndef _Included_com_jni_FFmpeg
#define _Included_com_jni_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_FFmpeg
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_FFmpeg_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
